# Server configuration
server.port=8080

# Spring Application configuration
spring.application.name=bfhl

# Custom campus hiring metadata configuration
bfhl.user.id=shivani_prajapati_26052026
bfhl.user.email=shivani.prajapati@university.edu
bfhl.user.roll-number=CU12345678
